"""made changes to sports.db and users.db

Revision ID: 21e147c6c309
Revises: c7d265444965
Create Date: 2025-10-22 22:59:15.446160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e147c6c309'
down_revision = 'c7d265444965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_leagues', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('favorite_sports', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_sports')
        batch_op.drop_column('favorite_leagues')

    # ### end Alembic commands ###
