"""added status to plans db

Revision ID: 287ed02eada8
Revises: ff601468bb6b
Create Date: 2025-10-03 13:43:29.590993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287ed02eada8'
down_revision = 'ff601468bb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
