"""added stripe_price_id to plans db

Revision ID: 3ff15d2f56ef
Revises: ffd420f32f87
Create Date: 2025-10-03 10:46:33.241672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff15d2f56ef'
down_revision = 'ffd420f32f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###
