"""add reset_otp fields

Revision ID: 83ba308b7b9f
Revises: b378f1cee163
Create Date: 2025-10-14 13:58:43.605628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ba308b7b9f'
down_revision = 'b378f1cee163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_otp_expiry')
        batch_op.drop_column('reset_otp')

    # ### end Alembic commands ###
