"""removed unique sports key for sports.sport

Revision ID: b5e3c6b03c29
Revises: e8f3c33fcdde
Create Date: 2025-10-26 15:23:28.050623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e3c6b03c29'
down_revision = 'e8f3c33fcdde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sports_sport_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('sports_sport_key'), ['sport'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
