"""added sports.db and updated alerts

Revision ID: c7d265444965
Revises: 83ba308b7b9f
Create Date: 2025-10-22 15:14:49.469353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d265444965'
down_revision = '83ba308b7b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=250), nullable=True),
    sa.Column('league', sa.String(length=500), nullable=True),
    sa.Column('surebets', sa.Integer(), nullable=True),
    sa.Column('middles', sa.Integer(), nullable=True),
    sa.Column('values', sa.Integer(), nullable=True),
    sa.Column('last_count', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_sports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('webpush_info', sa.JSON(), nullable=True))
        batch_op.drop_column('favorite_team')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('setting_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.alter_column('setting_name',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_team', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('webpush_info')
        batch_op.drop_column('favorite_sports')

    op.drop_table('sports')
    # ### end Alembic commands ###
