"""added unique sports

Revision ID: e8f3c33fcdde
Revises: 21e147c6c309
Create Date: 2025-10-26 13:56:23.921523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f3c33fcdde'
down_revision = '21e147c6c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['league'])
        batch_op.create_unique_constraint(None, ['sport'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
