"""added stripe_price_id to plans db

Revision ID: ff601468bb6b
Revises: 3ff15d2f56ef
Create Date: 2025-10-03 10:47:01.934534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff601468bb6b'
down_revision = '3ff15d2f56ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_price_id', sa.Text(), nullable=True))
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('stripe_price_id')

    # ### end Alembic commands ###
